### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by quinkennedy** [matthewepler/recodesite#7]
When I click the "add" button for an artwork, I get a `500 Internal Server Error`. I am hoping there is a log somewhere that would point to the problem.

http://www.recodeproject.com/submit/v1n2detail-from-tapestry

**Comment by matthewepler** [comment]
Will look into this this evening. Thanks, Quin.

**Comment by matthewepler** [comment]
Obv. didn't get to this. Will try again. Thanks for your patience.

**Comment by quinkennedy** [comment]
I am trying to get a local dev environment set up. Is there a way to populate the MongoDB with the appropriate schema and perhaps some sample data? I'm assuming the following error message is due to an empty DB:

`AttributeError: 'ObjectIdField' object has no attribute 'help_text'`

**Comment by quinkennedy** [comment]
looking into it a bit more, it seems my error might be coming from wtforms. What version of mongodb and mongoengine are you using? maybe when I do `pip install -r requirements.txt` I'm installing too new a version of something.

I have (among other things):
* mongodb 3.0.7
* wtforms 2.0.2
* flask-mongoengine 0.7.4
* mongoengine 0.10.5

**Comment by matthewepler** [comment]
Quinn,

Sounds like the initial error is caused by a form error. I added default entries to the form processing and that should make it less likely to throw an error if the form is not filled out exactly right. 

If it's not that, then you're right - logs would be the place to see what is happening and a local development would be the best way to achieve that since heroku logs may not have enough detail. 

As for the requirements.txt, this is what I have in mine: 
Flask==0.10
Mongoengine
unidecode
Flask-mongoengine
requests==0.14.1
boto
Flask-Bcrypt==0.5.2
Flask-Login==0.1.2
pymongo==2.9

Of course, I built this a few years ago and am not an active Python/Flask developer so there are probably huge holes in here that need mending. Please let me know how else I can help you solve your issue. 

If you need the mongodb ENV variables, let me know. You've been with the project a long time and I'd trust you to use them to download a local copy to play with as long as you didn't push anything back. In any case, I have auto backups running. 

M
